"""Summarize news articles using Langchain and OpenAI."""

import logging
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from config import Config

logger = logging.getLogger(__name__)


class NewsSummarizer:
    """Summarizes news articles using OpenAI via Langchain."""

    def __init__(self, model_name: str = None):
        """Initialize the summarizer.

        Args:
            model_name: LLM model to use (uses Config if not provided)
        """
        self.model_name = model_name or Config.MODEL_NAME
        self.llm = ChatOpenAI(
            model=self.model_name,
            temperature=0.7,
            api_key=Config.OPENAI_API_KEY,
        )

        # Create the summarization prompt template
        self.summary_prompt = PromptTemplate(
            input_variables=["articles"],
            template="""You are a music news curator. Summarize the following music news articles into a friendly, 
engaging daily digest. Include the most interesting stories, trends, and updates from the music world.

Format the summary with:
1. A catchy headline
2. 3-5 key stories with brief descriptions
3. A fun fact or trend observation
4. Sources and links for further reading

Keep it concise but informative (around 500-800 words). Make it engaging for music enthusiasts!

Articles:
{articles}

Daily Music News Digest:""",
        )

        # Create the chain using LCEL (Langchain Expression Language)
        self.chain = self.summary_prompt | self.llm | StrOutputParser()

    def summarize(self, articles_text: str) -> str:
        """Summarize articles using OpenAI.

        Args:
            articles_text: Formatted articles text

        Returns:
            Summary of the articles
        """
        try:
            logger.info("Generating summary with OpenAI...")
            response = self.chain.invoke({"articles": articles_text})
            logger.info("✅ Summary generated successfully")
            return response

        except Exception as e:
            logger.error(f"Failed to generate summary: {e}")
            raise

    def create_email_body(self, summary: str) -> str:
        """Create a formatted email body.

        Args:
            summary: The news summary

        Returns:
            Formatted email body HTML
        """
        html_body = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 600px;
            margin: 0 auto;
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
            text-align: center;
        }}
        .header h1 {{
            margin: 0;
            font-size: 28px;
        }}
        .content {{
            color: #555;
            line-height: 1.8;
        }}
        .content p {{
            margin: 10px 0;
        }}
        .footer {{
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            text-align: center;
            color: #999;
            font-size: 12px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🎵 Daily Music News Digest</h1>
            <p>Your curated music world update</p>
        </div>
        <div class="content">
            {summary.replace(chr(10), '<br>')}
        </div>
        <div class="footer">
            <p>Generated by Daily Music News Bot</p>
            <p>Keep enjoying music! 🎶</p>
        </div>
    </div>
</body>
</html>
"""
        return html_body


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    
    # Test summarizer
    test_articles = """
    1. Taylor Swift Breaks Another Record
       Taylor Swift's latest album becomes fastest-selling album ever
    
    2. New Spotify Feature
       Spotify launches AI DJ feature to personalize playlists
    """
    
    summarizer = NewsSummarizer()
    summary = summarizer.summarize(test_articles)
    print(summary)
